# BOD configuration

# OII indices
BOD_FID_IDX=1
BOD_IID_IDX=2
BOD_PID_IDX=3
BOD_MID_IDX=4
BOD_SEX_IDX=5

# OPI indices
BOD_CHR_IDX=1
BOD_PROBE_ID_IDX=2
BOD_POS_IDX=3
BOD_GENE_ID_IDX=4
BOD_GENE_STRAND_IDX=5 
