# Phenotype file configuration

IID_IDX=1 # When IID is used instead of barcode

BARCODE_IDX=1
YEAR_IDX=2
CG_IDX=3 # COVAR
ADJ_FW_KG_IDX=4
HEIFER_AGE_JOINING_IDX=5 #COVAR
HEF_AGE_AT_PREGTEST_IDX=6 #CORRELATED
HEF_WKS_PREG_IDX=7 #COVAR PREGNANCY STATUS
HEIFER_AGE_CALVING_IDX=8 # PHENO (AFC)
HEF_DTC_IDX=9
MATE_IN_DATE_IDX=10 #COVAR
CALF_IDENT_IDX=11
CALF_SEX_IDX=12 #MB COVAR
CALF_YOB_IDX=13
CALVING_SUCCESS_IDX=14
CLASS_CALVING_IDX=15
MATE_GROUP_IDX=16
YEAR_MATE_IDX=17 #COVAR
MONTH_MATE_IDX=18 #not a covar, as only october was used
DATE_DIFF_IDX=19 #CHECK
HEF_PREG_SUCCESS_IDX=20 #COVAR
PREG_ST_BINARY=21 # NEW

